### ISSUE TITLE
`str(r.now())` or `repr(r.now())` raise RuntimeError in python 3.7+

### ISSUE THREAD

**Issue by nlevitt** [rethinkdb/rethinkdb-python#110]
**Describe the bug**

This happens in python 3.7 but seemingly not earlier versions.
```
>>> from rethinkdb import RethinkDB
>>> r = RethinkDB()
>>> r.now()
Traceback (most recent call last):
  File "/Users/nlevitt/workspace/doublethink/doublethink-ve37/lib/python3.7/site-packages/rethinkdb/errors.py", line 246, in __iter__
    for sub in next(itr):
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nlevitt/workspace/doublethink/doublethink-ve37/lib/python3.7/site-packages/rethinkdb/ast.py", line 147, in __repr__
    return "<RqlQuery instance: %s >" % str(self)
  File "/Users/nlevitt/workspace/doublethink/doublethink-ve37/lib/python3.7/site-packages/rethinkdb/ast.py", line 144, in __str__
    return printer.print_query()
  File "/Users/nlevitt/workspace/doublethink/doublethink-ve37/lib/python3.7/site-packages/rethinkdb/errors.py", line 202, in print_query
    return ''.join(self.compose_term(self.root))
  File "/Users/nlevitt/workspace/doublethink/doublethink-ve37/lib/python3.7/site-packages/rethinkdb/errors.py", line 251, in __iter__
    for sub in token:
RuntimeError: generator raised StopIteration
```

Can be a major problem if code tries to log a query before running it, for example.

**To Reproduce**
1. see above

**Expected behavior**
Return a reasonable stringification.

**Screenshots**

**System info**
 - OS: tested on mac, linux
 - RethinkDB Version: any
 - Python client version: 2.4.1, 2.3.0

**Additional context**

**Comment by gabor-boros** [comment]
@nlevitt Sorry for the late reply. I'll investigate this as soon as I have time.

**Comment by gabor-boros** [comment]
@nlevitt `r.now()` works, but the documentation is wrong. The "right" usage is:
```python
>>> r.now().run(conn)
datetime.datetime(2019, 4, 25, 18, 48, 25, 317000, tzinfo=<rethinkdb.ast.RqlTzinfo object at 0x10de37c50>)
```

This is a bit weird for me. @grandquista Is this worked like this before?

**Comment by gabor-boros** [comment]
Opened a PR to fix this. I'll need to add unit/integration tests tomorrow.

**Comment by gabor-boros** [comment]
@nlevitt the fix is on master. Could you please try it out by installing from source if it is working for you as well? (The tests should ensure that its working but to double check it)

**Comment by nlevitt** [comment]
Um... how do I install from source? 
```
(rethinkdb-python-ve3)$ pip install -e .
Obtaining file:///Users/nlevitt/workspace/rethinkdb-python
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/nlevitt/workspace/rethinkdb-python/setup.py", line 30, in <module>
        from rethinkdb.version import VERSION
      File "/Users/nlevitt/workspace/rethinkdb-python/rethinkdb/__init__.py", line 88, in <module>
        r = RethinkDB()
      File "/Users/nlevitt/workspace/rethinkdb-python/rethinkdb/__init__.py", line 36, in __init__
        from rethinkdb import (
      File "/Users/nlevitt/workspace/rethinkdb-python/rethinkdb/_dump.py", line 35, in <module>
        from rethinkdb import _export, utils_common
      File "/Users/nlevitt/workspace/rethinkdb-python/rethinkdb/_export.py", line 38, in <module>
        import six
    ModuleNotFoundError: No module named 'six'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /Users/nlevitt/workspace/rethinkdb-python/
```

10 minutes of playing with it and I still haven't figured out how to install?

**Comment by gabor-boros** [comment]
Sorry, I forgot to describe it, my shame:
- Clone the repo
- Run “make prepare”
- Run “python setup.py install”

I hope I did not forgot anything

**Comment by nlevitt** [comment]
Thanks. Works for me!

**Comment by gabor-boros** [comment]
Then I’m closing this issue
