### ISSUE TITLE
Issue building with Docker with 2.4.2

### ISSUE THREAD

**Issue by davammas** [rethinkdb/rethinkdb-python#116]
**Describe the bug**
When building docker container to the 2.4.2 I get the following error. This has been tested on two different docker containers that utilize the RethinkDB Python Driver. I have had to use the 2.4.1 driver in order to have docker run.

    from rethinkdb import RethinkDB
  File "/usr/local/lib/python3.6/dist-packages/rethinkdb/__init__.py", line 29, in <module>
    __version__ = version.VERSION
AttributeError: module 'rethinkdb.version' has no attribute 'VERSION'

**Comment by epequeno** [comment]
steps to reproduce
```
$ docker --version
Docker version 18.09.5-ce, build e8ff056dbc

$ cat requirements.txt 
rethinkdb

$ cat Dockerfile
from python:3
COPY requirements.txt .
RUN pip install -r requirements.txt

$ docker build -t temp .
Sending build context to Docker daemon  3.072kB
Step 1/3 : from python:3
 ---> 954987809e63
Step 2/3 : COPY requirements.txt .
 ---> 2a5b08a98b45
Step 3/3 : RUN pip install -r requirements.txt
 ---> Running in c5289e4638c2
Collecting rethinkdb (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a2/a1/6a747546146c50f92b5e9a8ae215c28a0ab79330858a42dc7af101c0ad84/rethinkdb-2.4.2-py2.py3-none-any.whl (155kB)
Collecting six (from rethinkdb->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: six, rethinkdb
Successfully installed rethinkdb-2.4.2 six-1.12.0
Removing intermediate container c5289e4638c2
 ---> b1ef478ca207
Successfully built b1ef478ca207
Successfully tagged temp:latest

$ docker run --rm -it temp /bin/bash
root@630a6bf64e6d:/# python
Python 3.7.3 (default, Mar 27 2019, 23:40:30) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rethinkdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/rethinkdb/__init__.py", line 29, in <module>
    __version__ = version.VERSION
AttributeError: module 'rethinkdb.version' has no attribute 'VERSION'
```

**Comment by grandquista** [comment]
https://github.com/rethinkdb/rethinkdb-python/pull/106#discussion_r277151557

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gabor-boros** [comment]
@davammas @epequeno The issue has been fixed now, the fixed version is on PyPi.

```bash
$ docker build -t temp .
Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM python:3
 ---> 954987809e63
Step 2/3 : COPY requirements.txt .
 ---> ad1b1e13ab6b
Step 3/3 : RUN pip install -r requirements.txt
 ---> Running in 4175afef1c6b
Collecting rethinkdb (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/98/4b/b22065b2686f440f8eaa8a7326e96a442ce98b7b637d28529958b83b2128/rethinkdb-2.4.2.post1-py2.py3-none-any.whl (155kB)
Collecting six (from rethinkdb->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: six, rethinkdb
Successfully installed rethinkdb-2.4.2.post1 six-1.12.0
Removing intermediate container 4175afef1c6b
 ---> 2184c7a55fbd
Successfully built 2184c7a55fbd
Successfully tagged temp:latest

$ docker run --rm -it temp /bin/bash

$ root@816375afa197:/# python
Python 3.7.3 (default, Mar 27 2019, 23:40:30)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rethinkdb import r
>>> from rethinkdb.version import VERSION
>>> print(VERSION)
2.4.2.post1
```
