### ISSUE TITLE
Error restoring a database

### ISSUE THREAD

**Issue by Dwigoric** [rethinkdb/rethinkdb-python#157]
This is the output that I receive when trying to restore (on root):
```
Extracting archive file...
  Done (0 seconds)
Traceback (most recent call last):
  File "/usr/local/bin/rethinkdb-restore", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/_restore.py", line 284, in main
    do_restore(options)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/_restore.py", line 255, in do_restore
    sources = _import.parse_sources(options)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/_import.py", line 1444, in parse_sources
    primary_key, indexes, write_hook = parse_info_file(info_path)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/_import.py", line 1346, in parse_info_file
    return primary_key, indexes, write_hook
UnboundLocalError: local variable 'write_hook' referenced before assignment
```

RethinkDB version:
```
rethinkdb 2.3.6.srh.1~0bionic (CLANG 6.0.0 (tags/RELEASE_600/final))
```

The python driver is at version 2.4.1.

**Comment by gabor-boros** [comment]
This issue was fixed in 5056bce8c0c9d254399db0d5e319cf4b02f52172. The functionality is working with 2.4.4.post1 for sure.
