### ISSUE TITLE
Restoring doesn't pick up primary_key from info files

### ISSUE THREAD

**Issue by meatcar** [rethinkdb/rethinkdb-python#171]
**Describe the bug**
We upgraded RethinkDB from 2.3.6 to 2.4.0, and the driver accordingly, rebuilt indexes. Now, dumps generated by the most recent python driver (2.4.4.post1) fail when restoring, with every table with a `primary_key` that isn't `id` failing as follows:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rethinkdb/_import.py", line 400, in read_to_queue
    for batch in self.batches(warning_queue=warning_queue):
  File "/usr/local/lib/python3.6/dist-packages/rethinkdb/_import.py", line 326, in batches
    self.setup_table()
  File "/usr/local/lib/python3.6/dist-packages/rethinkdb/_import.py", line 271, in setup_table
    (self.db, self.table, primary_key, self.primary_key))
RuntimeError: Error: table mydb.settings primary key was `id` rather than the expected: name
```
Here is a simple info + table file from the dump:
```
$ cat settings.info
{"db": {"id": "adb308f5-6d96-4e56-8002-911fb0676582", "name": "mydb", "type": "DB"}, "doc_count_estimates": [2], "id": "ccaf09fa-fb79-4c95-9db1-2f1f591cd8d6", "indexes": [], "name": "settings", "primary_key": "name", "type": "TABLE", "write_hook": null}
$ cat settings.json
[
{"name": "counter", "value": 30750}
]
```

**To Reproduce**
1. Upgrade a 2.3.6 DB to 2.4.0
2. Spin up our DB: `docker run --rm -v /var/lib/rethinkdb:/data --name db -it rethinkdb`
3. Spin up a fresh DB: `docker run --rm --name newdb -it rethinkdb`
4. Get the latest rethinkdb python client:
    ```
    docker run --rm --link db -v /var/lib/rethinkdb:/data -it rethinkdb bash
    apt update && apt install -y python3-pip && pip3 install             # inside bash
    ```
4. Dump the DB (inside bash): 
    ```
    # rethinkdb dump -c db
    ```
5. Try to restore the DB: 
    ```
    # rethinkdb restore -c newdb $(ls rethinkdb_dump_*.tar.gz | tail -n1)
    ```

**Expected behavior**
The restore succeeds. 

**System info**
 - OS: Debian 9
 - RethinkDB Version: 2.4.0 (as provided by docker)
 - Python client version: 2.4.4.post1

**Additional context**
Using the `2.3.0.post6` client works fine, just like in #157

**Comment by gabor-boros** [comment]
Hello @meatcar 👋 

Thank you for the well detailed report! I’ll check it as soon as I can. (Probably tomorrow morning)

**Comment by gabor-boros** [comment]
Hello, today I'll be not able to investigate this issue, tomorrow I'll have more time probably.

**Comment by gabor-boros** [comment]
@meatcar I was able to identify and fix this issue. Could you please try out the fix introduced in the linked PR?

**Comment by meatcar** [comment]
@gabor-boros the fix works, thanks. 👍

Just a note, I tried to install the package from the repo and ran into an error:
```
rethinkdb-python# python --version
Python 3.6.9
rethinkdb-python# pip --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
rethinkdb-python# make prepare
rethinkdb-python# pip install -r requirements.txt
...
rethinkdb-python# pip install .
Processing /tmp/rethinkdb-python
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-03goz71h-build/setup.py", line 59, in <module>
        long_description=open('README.md', 'r+').read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2743: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-03goz71h-build/
```
The following fixed the error, and the install went through fine:
```
rethinkdb-python# git diff
diff --git a/setup.py b/setup.py
index 3d87c6a..25194f9 100644
--- a/setup.py
+++ b/setup.py
@@ -56,7 +56,7 @@ setuptools.setup(
     zip_safe=True,
     version=VERSION,
     description='Python driver library for the RethinkDB database server.',
-    long_description=open('README.md', 'r').read(),
+    long_description=open('README.md', 'r', encoding='utf-8').read(),
     long_description_content_type='text/markdown',
     url='https://github.com/RethinkDB/rethinkdb-python',
     maintainer='RethinkDB.',

```

**Comment by gabor-boros** [comment]
Ohh heck. We forgot the encoding. Thank you for pointing out! I’m glad that the fix worked, I’ll push the new version to pypi tomorrow morning 😇
